# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-rspec` gem.
# Please instead update this file by running `bin/tapioca gem async-rspec`.


# source://async-rspec//lib/async/rspec/version.rb#6
module Async; end

# source://async-rspec//lib/async/rspec/version.rb#7
module Async::RSpec; end

# source://async-rspec//lib/async/rspec/leaks.rb#10
Async::RSpec::Leaks = RSpec::Files::Leaks

# source://async-rspec//lib/async/rspec/memory.rb#11
Async::RSpec::Memory = RSpec::Memory

# source://async-rspec//lib/async/rspec/reactor.rb#16
module Async::RSpec::Reactor
  # source://async-rspec//lib/async/rspec/reactor.rb#17
  def notify_failure(exception = T.unsafe(nil)); end

  # source://async-rspec//lib/async/rspec/reactor.rb#21
  def run_in_reactor(reactor, duration = T.unsafe(nil)); end
end

# source://async-rspec//lib/async/rspec/version.rb#8
Async::RSpec::VERSION = T.let(T.unsafe(nil), String)
