inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
