services:
  alarm_server:
    build:
      context: .
    image: alarm_server
    container_name: alarm_server
    command: "./bin/server"
    env_file: .env
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8888:8888
    healthcheck:
      test: >
        bash -c '
          echo "PING" | nc 127.0.0.1 8888 | grep -q "PONG"
        '
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3
