apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.label }}
  labels:
    name: {{ .Values.app.label }}
    env: {{ .Values.app.environment }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{ .Values.app.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  {{- if eq .Values.app.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.app.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ .Values.app.label }}
  ports:
    - name: tcp
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.env.port }}
      protocol: TCP
