image:
  repository: "ghcr.io/josevictorferreira/alarm_server"
  tag: "latest"
  pullPolicy: Always

strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1
  minReadySeconds: 10

app:
  label: "alarm-server"
  command: ["./bin/server"]
  replicaCount: 1
  service:
    port: 8888
    type: LoadBalancer
    loadBalancerIP: 10.10.10.155
    annotations: {}
  env:
    port: "8888"
    address: 0.0.0.0
    mqtt_url: mqtt://rabbitmq-headless:1883
    mqtt_topic: alarms
    message_parser: icsee
    message_filters: log,alarm
    log_level: info
    log_output: stdout
    ntfy_enabled: "false"
    ntfy_url: https://ntfy.sh
    ntfy_topic: camera_alarms
  resources:
    requests:
      memory: 512Mi
      cpu: 30m
    limits:
      memory: 512Mi
  healthcheck_command:
    - bash
    - -c
    - echo "PING" | nc 127.0.0.1 8888 | grep -q "PONG"
