name: Production Build

on:
  release:
    types:
      - created

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USERNAME: $${{ github.actor }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CI_TOKEN }}

jobs:
  build:
    name: Build and Push
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.push.outputs.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
    - name: Run Docker Build (Push Image)
      if: success()
      id: push
      env:
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build . \
          --tag ${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY}:latest \
          --tag ${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY}:${IMAGE_TAG} \
          --cache-from type=registry,ref=${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY}:latest,mode=max \
          --cache-to type=inline \
          --push
